nohup: ignoring input
/workspaces/CoPPA-Stop-Search-Reasonable-Grounds/backend/settings.py:241: UserWarning: A custom validator is returning a value other than `self`.
Returning anything other than `self` from a top level model validator isn't supported when validating via `__init__`.
See the `model_validator` docs (https://docs.pydantic.dev/latest/concepts/validators/#model-validators) for more details.
  super().__init__(**data)
ERROR:backend.search_setup:Required environment variables are not set. Search components setup failed.
Traceback (most recent call last):
  File "/workspaces/CoPPA-Stop-Search-Reasonable-Grounds/app.py", line 1159, in <module>
    asyncio.run(hypercorn.asyncio.serve(app, config))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/vscode/.local/lib/python3.10/site-packages/hypercorn/asyncio/__init__.py", line 44, in serve
    await worker_serve(
  File "/home/vscode/.local/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 91, in worker_serve
    sockets = config.create_sockets()
  File "/home/vscode/.local/lib/python3.10/site-packages/hypercorn/config.py", line 206, in create_sockets
    insecure_sockets = self._create_sockets(self.bind)
  File "/home/vscode/.local/lib/python3.10/site-packages/hypercorn/config.py", line 273, in _create_sockets
    sock.bind(binding)
OSError: [Errno 98] Address already in use
